### PR TITLE
Updating documentation to use VVV over existing Vagrant setup

### PR DESCRIPTION
**Pull request by rclations**
## Changes
- Removed all vagrant files
- Updated vagrant setup documentation to direct users to the Largo documentation, centralizing the documentation on Vagrant setup.
## Why?

[VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) offers additional benefits specifically for our work in the WordPress community:
- Large user base, with an active community and continuing feature development.
- Simpler setup
- Less bugs, and more community support for any bugs that we may find
- Additional tools specifically for WordPress development

In addition, by adopting standard tools widely used in the community, we grow our ability to attract new developers to contribute to our projects.

This would fix issues #41 & #47, by removing the functionality they address in favor of using VVV.

### CODE REVIEW

**Comment by benlk** [comment]
How does VVV configure apache and mysql to be accessible to the host machine? The deploy tools assume the existence of the mysql user `root` with password `root`.

**Comment by rclations** [comment]
[http://vvv.dev/](http://vvv.dev/) gives you a dashboard that lists were all of your sites are and also access to other server tools

phpMyAdmin is accessible at [http://vvv.dev/database-admin/](http://vvv.dev/database-admin/)

for db access via command line you can just `vagrant ssh` in the vagrant repo then you can do anything you need on the machine.

Does that answer the question?

**Comment by benlk** [comment]
It does somewhat, but.

When running `fab vagrant.reload_db:dump.sql,database` to put a new copy of a database into the VM, [vagrant.reload_db](https://github.com/INN/deploy-tools/blob/master/fablib/vagrant/__init__.py#L47) calls [helpers.reload_db](https://github.com/INN/deploy-tools/blob/master/fablib/helpers.py#L117) calls helpers.destroy_db, helpers.create_db, and helpers.load_db, each of which calls something like `local('mysqldump -h %(db_host)s -u %(db_user)s -p%(db_pass)s --quick %(db_name)s > %(dump_file)s' % env)`: running a `mysql` command on the host computer to connect to the guest VM, using the credentials set in [vagrant/__init__.py](https://github.com/INN/deploy-tools/blob/master/fablib/vagrant/__init__.py#L9-L11):

```py
env.vagrant_host = '192.168.33.10'
env.vagrant_db_user = 'root'
env.vagrant_db_pass = 'root'
```

This PR changes the host to 192.168.50.4, but if we wanted to continue using the fab tools for managing databases instead of phpMyAdmin or mysql directly on the vagrant guest, are the db user and password the same? Will the username and password need to be updated in this PR as well?

**Comment by rclations** [comment]
Ah, that makes sense. I think from what you described everything should still work

You can access mysql by using the host IP address, per https://github.com/varying-vagrant-vagrants/vvv/wiki/Connecting-to-MySQL

and root/root is standard in the VVV setup for MySQL so we should be good there are well

**Comment by benlk** [comment]
Excellent. 👍

**Comment by benlk** [comment]
@rclations, as we approach the anniversary of this PR, should we update it to use Valet, or just merge it for VVV coverage now?

**Pull request merged**
